### ISSUE TITLE
SSR and Loadable results in unexpected token

### ISSUE THREAD

**Issue by tonilaukka** [btholt/complete-intro-to-react-v4#10]
If you follow the course and the do all the work in the same branch the SSR section won't run unless you add babel-plugin-syntax-dynamic-import and update .babelrc like this:

```
{
  "presets": [
    "react",
    [
      "env",
      {
        "targets": {
          "browsers": ["last 2 versions"]
        }
      }
    ]
  ],
  "plugins": ["transform-class-properties", "syntax-dynamic-import"]
}
```

**Comment by 1Marc** [comment]
Strange. The SSR solution branch works fine for me without this.

**Comment by 1Marc** [comment]
The code-splitting branch also works. Closing because I can't duplicate this behavior.

**Comment by sohara** [comment]
@1Marc The reason you weren't able to duplicate this issue is because the ssr branch does not have this commit in its history: https://github.com/btholt/complete-intro-to-react-v4/commit/1ffe36740e23fd5c7fcf154ffc0325e48a825d9d

In other words, the state of the repo does not reflect of the state of the project if you were following allowing with the course.

I am unfortunately unable to work around this issue using @tonilaukka's suggestion. I'm not sure what has changed, perhaps they had a specific version of the plugin installed.

**Comment by sohara** [comment]
Just a follow up, I was able to get this to work using @tonilaukka's solution when I upgrading my older node version (8.9.x) to current LTS (10.14.1).
